apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-workers
  namespace: prometheus-system
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      ray.io/node-type: worker
  podMetricsEndpoints:
    - port: metrics
      interval: 5s
      scrapeTimeout: 4s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
  podTargetLabels:
    - ray.io/cluster
    - ray.io/group
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-head
  namespace: prometheus-system
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      ray.io/node-type: head
  podMetricsEndpoints:
    - port: metrics
      interval: 5s
      scrapeTimeout: 4s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
    - port: as-metrics
      interval: 5s
      scrapeTimeout: 4s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
    - port: dash-metrics
      interval: 5s
      scrapeTimeout: 4s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
  podTargetLabels:
    - ray.io/cluster
