apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test2
  region: us-west-2

nodeGroups:
  - name: head-nodes
    instanceType: m5.8xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 1
    volumeSize: 256
    labels:
      ray-node-type: head

  - name: worker-nodes
    instanceType: m5.4xlarge
    desiredCapacity: 5
    minSize: 0
    maxSize: 5
    volumeSize: 1024
    amiFamily: Bottlerocket
    labels:
      ray-node-type: worker
