apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gpularge
  region: us-east-1

nodeGroups:
  - name: head-nodes
    instanceType: g4dn.8xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 1
    volumeSize: 256
    labels:
      ray-node-type: head

  - name: worker-nodes
    instanceType: g4dn.4xlarge
    desiredCapacity: 10
    minSize: 10
    maxSize: 10
    volumeSize: 1024
    amiFamily: Bottlerocket
    labels:
      ray-node-type: worker
