apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test7
  region: us-west-2

nodeGroups:
  - name: head-nodes
    instanceType: g4dn.12xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 1
    volumeSize: 1024
    labels:
      ray-node-type: head
  - name: worker-nodes
    instanceType: m5.16xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 1
    volumeSize: 1024
    amiFamily: Bottlerocket
    labels:
      ray-node-type: worker
