{
 "title": "Customized Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Node Communication (Train)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ray_train_node_network", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node Communication (Pretrain)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ray_pretrain_node_network", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pretrain Time Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "ray_pretrain_time_cost", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Train Time Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "ray_train_time_cost", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}