{{- if .Values.rbacEnable }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{ include "kuberay-operator.labels" . | nindent 4 }}
  name: {{ include "kuberay-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name  }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kuberay-operator.fullname" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
{{- end }}
