# Project Information
site_name: KubeRay Docs
site_url: https://ray-project.github.io/kuberay

# Repository
repo_name: ray-project/kuberay
repo_url: https://github.com/ray-project/kuberay
edit_uri: ""

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

# Navigation
nav:
  - Home:
    - Welcome: index.md
    - Getting Started:
      - Installation:
        - YAML: deploy/installation.md
        - Helm: deploy/helm.md
        - Helm (Cluster): deploy/helm-cluster.md
      - Docker Images: deploy/docker.md
  - Components:
    - KubeRay Operator: components/operator.md
    - KubeRay API Server: components/apiserver.md
    - KubeRay CLI: components/cli.md
  - Features:
    - RayService: guidance/rayservice.md
    - RayJob: guidance/rayjob.md
    - Ray GCS Fault Tolerance: guidance/gcs-ft.md
    - Autoscaling: guidance/autoscaler.md
    - Networking:
      - Ingress: guidance/ingress.md
      - TLS: guidance/tls.md
    - Monitoring and Observability:
      - Observability: guidance/observability.md
      - Prometheus and Grafana: guidance/prometheus-grafana.md
      - Profiling: guidance/profiling.md
    - Security:
      - IAM Roles (AWS EKS): guidance/aws-eks-iam.md
      - Pod Security: guidance/pod-security.md
    - Integrations:
      - KubeRay with MCAD: guidance/kuberay-with-MCAD.md
      - KubeRay with Volcano: guidance/volcano-integration.md
      - Kubeflow Integration: guidance/kubeflow-integration.md
    - Best Practices:
      - Executing Commands: guidance/pod-command.md
      - Worker Reconnection: best-practice/worker-head-reconnection.md
  - Troubleshooting:
    - FAQ: guidance/FAQ.md
    - RayService Troubleshooting: guidance/rayservice-troubleshooting.md
  - Development:
    - Developer Guide: development/development.md
    - Release Process:
      - Overview: development/release.md
      - Generating the Changelog: release/changelog.md
      - Releasing the Helm Chart: release/helm-chart.md
  - Reference:
    - API Reference: reference/api.md

# Customization
extra:
  version:
    provider: mike

plugins:
  - tags
  - search

# Markdown Extension
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
