# general:
  model: 'SelfTrain'

# dataset
  dataset: "IMDB-BINARY"
  is_multiple_dataset: False
  datapath: './data'
  convert_x: False
  overlap: False

# setup
  device: 'cpu'
  seed: 10

# model_parameters
  num_trainers: 10
  local_epoch: 1
  lr: 0.001
  weight_decay: 0.0005
  nlayer: 3
  hidden: 64
  dropout: 0.5
  batch_size: 128

# output
  outbase: './outputs'
  save_files: False
