dual_weight: 5.e-4
aug_lagrange_rho: 6.e-4
model_lr: 0.64
model_regularisation: 2.e-3
dual_lr: 1.e-2
num_local_iters: 100
train_rounds: 1
global_rounds: 1
gamma: 0.2
attn_func_parameter: 0.2
# lambda x: AttnFunction(x, 0.2)
attn_func_domain: [-10, 10, 1600]
sample_probab: 5.
hidden_dim1: 64
hidden_dim2: 16
num_heads1: 8
num_heads2: 8
max_deg: 18
neighbour_std_control: 1.
hidden_dim: 8
num_heads : 8
device: cpu


# dataset: ogbn-arxiv
dataset: cora
n_trainer: 1
num_layers: 2
num_hops: 2
gpu: True
momentum: 0.0
iid_beta: 10000
logdir: ./runs
device: cpu
optim_kind: SGD
glob_comm: FedAvg
optim_reset: True
dampening: 0.0
limit_node_degree: 60
# method: DistributedGAT
# method: CentralizedGAT
method: FedGAT
batch_size: 32
vecgen: True
communication_grad: False
