dual_weight: 5.e-4
aug_lagrange_rho: 5.e-3
model_lr: 0.01
model_regularisation: 2.e-3
dual_lr: 1.e-2
num_local_iters: 1
train_rounds: 20
gamma: 0.2
attn_func_parameter: 0.2
# lambda x: AttnFunction(x, 0.2)
attn_func_domain: [-5, 5, 500]
sample_probab: 1.
hidden_dim: 8
num_heads: 8
max_deg: 16

# dataset: ogbn-arxiv
dataset: ogbn-arxiv
fedtype: fedgat
global_rounds: 5 # 5
local_step: 10
learning_rate: 0.1
n_trainer: 5
num_layers: 2
num_hops: 2
gpu: false
momentum: 0.0
iid_beta: 10000
logdir: ./runs
device: cpu
optim_kind: Adam
glob_comm: FedAvg
optim_reset: False
dampening: 0.0
