dual_weight: 5.e-3
aug_lagrange_rho: 2.e-3
model_lr: 4.
model_regularisation: 7.5e-4
dual_lr: 0.4
num_local_iters: 2 # 3
train_rounds: 40 # 300
gamma: 0.2
attn_func_parameter: 0.2
# lambda x: AttnFunction(x, 0.2)
attn_func_domain: [-4, 4, 300]
sample_probab: 0.4
hidden_dim: 8
num_heads: 2 # 8
max_deg: 6

dataset: cora
fedtype: fedgat
global_rounds: 2 # 5
local_step: 2
learning_rate: 0.1
n_trainer: 5
num_layers: 2
num_hops: 2
gpu: false

iid_beta: 10000
logdir: ./runs
device: cpu
