#ci:group=:yaml: Sample YAML tests

- label: 'Test RayCluster Sample YAMLs (nightly operator)'
  instance_size: large
  image: golang:1.20
  commands:
    - ./.buildkite/setup-env.sh
    # Build nightly KubeRay operator image
    - pushd ray-operator
    - IMG=kuberay/operator:nightly make docker-image
    - popd
    # Use nightly KubeRay operator image
    - source .venv/bin/activate && BUILDKITE_ENV=true OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_raycluster_yamls.py

- label: 'Test RayCluster Sample YAMLs (latest release)'
  instance_size: large
  image: golang:1.20
  commands:
    - ./.buildkite/setup-env.sh
    # Use KubeRay operator image from the latest release
    - source .venv/bin/activate && BUILDKITE_ENV=true OPERATOR_IMAGE=quay.io/kuberay/operator:v1.1.0 python3 tests/test_sample_raycluster_yamls.py

- label: 'Test RayJob Sample YAMLs (nightly operator)'
  instance_size: large
  image: golang:1.20
  commands:
    - ./.buildkite/setup-env.sh
    # Build nightly KubeRay operator image
    - pushd ray-operator
    - IMG=kuberay/operator:nightly make docker-image
    - popd
    # Use nightly KubeRay operator image
    - source .venv/bin/activate && BUILDKITE_ENV=true OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_rayjob_yamls.py

- label: 'Test RayJob Sample YAMLs (latest release)'
  instance_size: large
  image: golang:1.20
  commands:
    - ./.buildkite/setup-env.sh
    # Use KubeRay operator image from the latest release
    - source .venv/bin/activate && BUILDKITE_ENV=true OPERATOR_IMAGE=quay.io/kuberay/operator:v1.1.0 python3 tests/test_sample_rayjob_yamls.py

- label: 'Test RayService Sample YAMLs (nightly operator)'
  instance_size: large
  image: golang:1.20
  commands:
    - ./.buildkite/setup-env.sh
    # Build nightly KubeRay operator image
    - pushd ray-operator
    - IMG=kuberay/operator:nightly make docker-image
    - popd
    # Use nightly KubeRay operator image
    - source .venv/bin/activate && BUILDKITE_ENV=true OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_rayservice_yamls.py

- label: 'Test RayService Sample YAMLs (latest release)'
  instance_size: large
  image: golang:1.20
  commands:
    - ./.buildkite/setup-env.sh
    # Use KubeRay operator image from the latest release
    - source .venv/bin/activate && BUILDKITE_ENV=true OPERATOR_IMAGE=quay.io/kuberay/operator:v1.1.0 python3 tests/test_sample_rayservice_yamls.py
