apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "kuberay-apiserver.labels" . | indent 4 }}
{{- if .Values.labels }}
{{- toYaml .Values.labels | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "kuberay-apiserver.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "kuberay-apiserver.name" . }}
        app.kubernetes.io/name: {{ .Release.Name }}
        {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          {{- toYaml .Values.containerPort | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
      {{- if .Values.security }}
      - name: security-proxy-container
        image: "{{ .Values.security.proxy.repository }}:{{ .Values.security.proxy.tag }}"
        imagePullPolicy: {{ .Values.security.proxy.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.security.env.HTTP_LOCAL_PORT }}
            protocol: TCP
          - name: grpc
            containerPort: {{ .Values.security.env.GRPC_LOCAL_PORT }}
            protocol: TCP
        env:
          {{- range $key, $value := .Values.security.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $port := .Values.containerPort  }}
            {{- if eq $port.name "http" }}
          - name: "HTTP_REMOTE_PORT"
            value: {{ $port.containerPort | quote }}
            {{- end }}
            {{- if eq $port.name "grpc" }}
          - name: "GRPC_REMOTE_PORT"
            value: {{ $port.containerPort | quote }}
            {{- end }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- end }}

      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
