{{- if .Values.rbacEnable }}
{{- if .Values.singleNamespaceInstall }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "kuberay-apiserver.labels" . | indent 4 }}
  name: {{ include "kuberay-apiserver.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name  }}
  namespace: {{ .Release.Namespace }}
roleRef:
  {{- if .Values.singleNamespaceInstall }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
